### ISSUE TITLE
snekfetch dependency 3.4.0 broke request promises

### ISSUE THREAD

**Issue by sogehige** [1Computer1/twitch-emoticons#1]
```
/node_modules/twitch-emoticons/src/struct/EmoteFetcher.js:149
        return this._getRawTwitchEmotes().then(rawEmotes => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at EmoteFetcher.fetchTwitchEmotes (/node_modules/twitch-emoticons/src/struct/EmoteFetcher.js:149:42)
    at Object.<anonymous> (test.js:9:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by sogehige** [comment]
This is not snekfetch issue, v2 of api used for twitch emotes is dead and only accessible is v3
